### ISSUE TITLE
[등록페이지]  개발 시작 전 분업정리

### ISSUE THREAD

**Issue by Kim-Yeon-ho** [DeveloperAcademy-POSTECH/MC2-Team11-NDOM#10]
## 작업내용
- [x] 등록페이지 1,2,8 전반적인 UI 작업(도피)
- [x] 등록페이지 3~7 전반적인 UI 작업(하디), asset에 custom color 지정
-  고양이 커스텀페이지는 이번 작업 완료 후 같이 논의예정

## 스크린샷 
<p align="left">
<img width="150" alt="스크린샷 2022-06-07 오후 8 05 58" src="https://user-images.githubusercontent.com/81131715/172366808-2ee5f3f8-4e31-44fd-9359-14ef2fa18ba8.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 01 11" src="https://user-images.githubusercontent.com/81131715/172366831-9b3a0771-5757-4bb6-8712-0c5232a79ce2.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 01 23" src="https://user-images.githubusercontent.com/81131715/172366864-749a2750-6278-4f48-9629-052b4d5d11d1.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 01 31" src="https://user-images.githubusercontent.com/81131715/172366999-605d8cfc-e68c-4da4-9652-597f95198ae6.png">
</p>

<p align="left">
<img width="150" alt="스크린샷 2022-06-07 오후 8 01 50" src="https://user-images.githubusercontent.com/81131715/172367049-f520e2ca-e248-4e1b-a1d6-1e55c0587b5d.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 02 03" src="https://user-images.githubusercontent.com/81131715/172367076-7c65ec24-2d7c-4823-b8c8-205622aed47a.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 03 06" src="https://user-images.githubusercontent.com/81131715/172367262-658613e8-f87a-45ae-b48f-d18c3537a199.png">

<img width="150" alt="스크린샷 2022-06-07 오후 8 03 19" src="https://user-images.githubusercontent.com/81131715/172367293-9c10c679-8788-464c-82c8-9bb0f62dc7ba.png">

</p>

**Comment by wody-d** [comment]
까먹지 않기 위한 코멘트 작성 😴
아까 논의했던 부분 - 건강 태그 화면은 등록프로세스에서 빼기 반영
