### ISSUE TITLE
[개발 들어가기전 작업] 이미지 업로드

### ISSUE THREAD

**Issue by ddophi98** [DeveloperAcademy-POSTECH/MC2-Team11-NDOM#11]
## 작업내용
- 고양이 일러스트 올리기
- 얼룩 무늬 사진 올리기 (제목과 함께 쓰일 배경)
- 밥/물 그릇 일러스트 올리기
- 배경 일러스트 올리기
- 상자 일러스트 올리기 (고양이 등록을 위한 이미지)

## Reference
- https://www.shutterstock.com/ko/image-vector/simple-illustration-open-box-icon-isolated-1822954343
- https://www.shutterstock.com/ko/image-vector/dog-bowl-icon-food-water-isolated-2103157268
- https://www.shutterstock.com/ko/image-vector/many-cats-various-poses-outline-style-1377922469

**Comment by wody-d** [comment]
이미지 이름도 지어서 올려주시면 감사하겠습니다!
